### PR TITLE
[Feature] Adding poetry

### LINKED ISSUE #16: Killbutton not working
As testing in another branch I found an Error Message, that a request from the server could not been answered.
This has the consequence of the Kill-Button not working and having no countdown. The server send a 404 error. Pictures of the Admin page, js-response and server-console output below:

[admin.json](https://github.com/Nimuedaertya/reallife-quest-murder-game/files/15016952/admin.json)

image

image

### LINKED ISSUE #22: Missing requirements
To get started with the project, one has to install the requirements as listed in `requirements.txt` file.
Then, if I'm right, they should run the `init.sh` script.

**Issue**
Running `init.sh` raises `ModuleNotFoundError` due to missing packages in the requirements file. See sceenshots :
image
image

**Expected behavior**
There should be no error.

Adding missing requirements should address this.

### PR DESCRIPTION
**Pull request by Nimuedaertya**
Motivation
  - add dependency management
  - easier testing and quality assurcance
  
Related:
 - fixes #16 
 - fixes #22

### CODE REVIEW

**Comment by Limiria** [comment]
Not quite sure what that means, but with making the file executable it worked (chmod then ./init.sh).
image

**Comment by Limiria** [comment]
As well this warning showed up, that said it would in future versions become an error.
image

**Comment by Limiria** [comment]
Kill Button seems fixed, but the vampire has no Killbutton. Is this intended? 
image

**Comment by Nimuedaertya** [comment]
https://github.com/Nimuedaertya/reallife-quest-murder-game/commit/88f1ea8ca6e819e79cbdc7211d84df87b411aebf
fixed the bug related to the kill button not showing up

executable bash files added

package-mode = false added

**Pull request merged**
